FROM maven:3-openjdk-11 as dev

RUN apt-get update \
  && apt-get install git curl -y

WORKDIR /build

RUN git clone --depth=1 --progress --verbose https://github.com/questdb/questdb.git

WORKDIR /build/questdb

RUN mvn clean package -DskipTests -Dprofile.install-local-nodejs

ENV PATH=/build/questdb/core/node:/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

FROM dev as build

WORKDIR /build/questdb/core/target
RUN tar xvfz questdb-*-rt-linux-amd64.tar.gz

FROM debian:stretch-slim

WORKDIR /app

COPY --from=build /build/questdb/core/target/questdb-*-rt-linux-amd64 .

WORKDIR /app/bin

# QuestDB root directory
RUN mkdir -p /root/.questdb

# Expose database as volume
VOLUME /root/.questdb/db

# Make working folder the quest db folder
WORKDIR /root/.questdb

# bash prompt
RUN echo "PS1='🐳  \[\033[1;36m\]\h \[\033[1;34m\]\W\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'" > /root/.bashrc

# Make port 9000 available to the world outside this container
EXPOSE 9000/tcp
EXPOSE 8812/tcp
EXPOSE 9009/tcp

# Run questdb when the container launches
CMD ["/app/bin/java", "--add-exports", "java.base/jdk.internal.math=io.questdb", "-m", "io.questdb/io.questdb.ServerMain", "-d", "/root/.questdb", "-f"]